Repository BangBangBwa/Backend, pull requests merged in 2024-12, with the labels that each got.

#57 [BBB-92] 게시물 상세 조회 팔로우 여부 반환
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/resources/mybatis/map/post.xml
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
Labels: enhancement

#58 [BBB-93] 일반/방송인 게시물 목록 조회 통합
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/enums/Role.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostTypeProvider.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/controller/StreamerController.java
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
Labels: enhancement

#59 [BBB-84] 게시물 상세 조회 존재하지 않는 게시물일 경우 예외 처리
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
Labels: enhancement

#60 [BBB-65] 방송 계정 승인 대기 중 사용자 재신청 불가능하도록 변경
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PromoteValidator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/DuplicatePendingPromotionException.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/type/PostErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/PendingStreamerGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PendingStreamerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/service/PendingStreamerService.java
  src/main/resources/mybatis/map/pendingStreamer.xml
  src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
Labels: enhancement

#62 [BBB-75] 마이페이지 - 프로필 정보 조회, 요약 조회 비즈니스 로직 구현
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/SummaryMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Streamer.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/member.xml
  src/main/resources/mybatis/map/streamer.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/member/MemberIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/MemberProfileIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/MemberSummaryIntegrationTest.java
Labels: enhancement

#63 [BBB-95] Streamer 엔티티 및 테이블 수정
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/RandomStreamerProvider.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerParser.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PlatformDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/StreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Streamer.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageReader.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/DailyMessageRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/service/DailyMessageService.java
  src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagDto.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/streamer.xml
  src/main/resources/schema.sql
Labels: bug

#61 [BBB-94] 댓글 신고
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentCreator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentParser.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportCommentUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportValidator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/ReportCommentDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Comment.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/ReportComment.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/ReportCommentMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/ReportCommentRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/resources/mybatis/map/comment.xml
  src/main/resources/mybatis/map/reportComment.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
Labels: enhancement

#65 [BBB-75] 마이페이지 조회 - 관심분야, 방송분야 태그 처리
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/ProfileDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follow.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/enums/Interest.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/ProfileMapper.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/StreamerTagRepository.java
  src/main/java/com/bangbangbwa/backend/domain/tag/business/TagManager.java
  src/main/java/com/bangbangbwa/backend/domain/tag/common/entity/Tag.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/member.xml
  src/main/resources/mybatis/map/streamerTag.xml
  src/test/java/com/bangbangbwa/backend/domain/member/MemberProfileIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomString.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomStringGenerator.java
Labels: enhancement

#64 [BBB-97] 태그 목록 조회 API 구현
  src/main/java/com/bangbangbwa/backend/domain/tag/business/TagReader.java
  src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagListDto.java
  src/main/java/com/bangbangbwa/backend/domain/tag/controller/TagApi.java
  src/main/java/com/bangbangbwa/backend/domain/tag/controller/TagController.java
  src/main/java/com/bangbangbwa/backend/domain/tag/repository/TagRepository.java
  src/main/java/com/bangbangbwa/backend/domain/tag/service/TagService.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/tag.xml
Labels: documentation, enhancement

#66 [BBB-85] 방송인 최신 글 표시 팔로우 관련 작업
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReaderPostCreator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReaderPostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetLatestPostsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/ReaderPostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageCreator.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/entity/DailyMessage.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/DailyMessageRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/service/DailyMessageService.java
  src/main/resources/mybatis/map/post.xml
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/repository/PostRepositoryTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/repository/ReaderPostRepositoryTest.java
  src/test/java/com/bangbangbwa/backend/global/test/MyBatisTest.java
  src/test/java/com/bangbangbwa/backend/global/test/RedisTest.java
Labels: enhancement

#67 [BBB-75] 마이페이지 조회 getSummary 플랫폼 추가
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
  src/main/resources/mybatis/map/member.xml
  src/main/resources/mybatis/map/streamer.xml
  src/test/java/com/bangbangbwa/backend/domain/member/MemberProfileIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomString.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomStringGenerator.java
Labels: enhancement

#68 [BBB-87] 로그인 중 사용자가 게시물 상세 정보 후 해당 게시글을 읽은 게시물로 추가
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
Labels: enhancement

#71 [BBB-99] 회원가입 도메인 관련 수정사항 수정
  src/main/java/com/bangbangbwa/backend/domain/member/business/NicknameGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberNicknameDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/MemberMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/mybatis/map/member.xml
  src/main/resources/schema.sql
Labels: documentation, enhancement

#69 [BBB-98] 로그인 사용자 게시물 목록 맞춤 조회
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostProvider.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostRecommendationStrategy.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/java/com/bangbangbwa/backend/domain/tag/repository/MemberTagRepository.java
  src/main/resources/mybatis/map/post.xml
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/repository/PostRepositoryTest.java
Labels: enhancement

#74 [BBB-109] 팔로우/팔로워 목록 조회
  src/main/java/com/bangbangbwa/backend/domain/member/business/FollowReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/FollowDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/FollowerDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/FollowRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/mybatis/map/follow.xml
  src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/repository/FollowRepositoryTest.java
Labels: documentation, enhancement

#73 [BBB-108] 게시물 목록 조회
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/PostDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/resources/mybatis/map/post.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/repository/PostRepositoryTest.java
Labels: enhancement

#75 [BBB-110] 등업 대기 요청 조회
  src/main/java/com/bangbangbwa/backend/domain/admin/common/dto/GetPendingMembers.java
  src/main/java/com/bangbangbwa/backend/domain/admin/controller/AdminController.java
  src/main/java/com/bangbangbwa/backend/domain/admin/service/AdminService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/PendingStreamerReader.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PendingStreamerRepository.java
  src/main/resources/mybatis/map/pendingStreamer.xml
  src/test/java/com/bangbangbwa/backend/domain/streamer/common/business/PendingStreamerReaderTest.java
Labels: enhancement

#76 [BBB-47] 홍보 스트리머 랜덤 조회 API 구현
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/RandomStreamerProvider.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerParser.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerInterestedListMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/service/StreamerService.java
  src/main/java/com/bangbangbwa/backend/domain/tag/business/TagReader.java
  src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagDto.java
  src/main/java/com/bangbangbwa/backend/domain/tag/repository/TagRepository.java
  src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/streamer.xml
  src/main/resources/mybatis/map/tag.xml
Labels: bug, enhancement

#77 [BBB-111] 게시물 고정 등록/삭제
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/TogglePostPinDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostValidator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/MaxPinnedPostsExceededException.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/NotFoundPostOrPermissionException.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/type/PostErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/resources/mybatis/map/post.xml
  src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/repository/PostRepositoryTest.java
Labels: enhancement

#78 [BBB-112] 팔로우/언팔로우
  src/main/java/com/bangbangbwa/backend/domain/member/business/FollowCreator.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/FollowDeleter.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/FollowGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/FollowParser.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/FollowUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/ToggleFollowDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follow.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/FollowMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/NotFoundFollowException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/FollowErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/FollowRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/mybatis/map/follow.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/member/MemberTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/repository/FollowRepositoryTest.java
Labels: enhancement

#79 [BBB-113] 신고된 게시물 조회
  src/main/java/com/bangbangbwa/backend/domain/admin/common/dto/GetReportedPostsDto.java
  src/main/java/com/bangbangbwa/backend/domain/admin/controller/AdminController.java
  src/main/java/com/bangbangbwa/backend/domain/admin/service/AdminService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/ReportPostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/ReportPostDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/ReportPost.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/ReportPostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/ReportPostRepository.java
  src/main/resources/mybatis/map/reportPost.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/admin/controller/AdminTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/repository/ReportPostRepositoryTest.java
  src/test/java/com/bangbangbwa/backend/global/gson/LocalDateTimeAdapter.java
  src/test/java/com/bangbangbwa/backend/global/test/IntegrationTest.java
Labels: enhancement

#86 [BBB-122] TagDto 생성자 수정
  src/main/java/com/bangbangbwa/backend/domain/tag/common/dto/TagDto.java
Labels: bug

#83 [BBB-123] 게시물 목록 조회 일반/방송 모드 분리
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostProvider.java
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostTypeProvider.java
  src/main/java/com/bangbangbwa/backend/domain/post/service/PostService.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/service/StreamerService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/MemberPostRecommender.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/StreamerPostRecommender.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/controller/StreamerController.java
  src/main/resources/mybatis/map/post.xml
  src/test/java/com/bangbangbwa/backend/domain/post/PostIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/streamer/StreamerTest.java
Labels: enhancement

#87 [BBB-126] 스트리머 플랫폼 연동/제거 API 구현
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
  src/main/java/com/bangbangbwa/backend/domain/platform/business/PlatformReader.java
  src/main/java/com/bangbangbwa/backend/domain/platform/business/PlatformRelation.java
  src/main/java/com/bangbangbwa/backend/domain/platform/business/PlatformValidator.java
  src/main/java/com/bangbangbwa/backend/domain/platform/common/dto/PlatformDto.java
  src/main/java/com/bangbangbwa/backend/domain/platform/common/dto/PlatformListDto.java
  src/main/java/com/bangbangbwa/backend/domain/platform/common/dto/StreamerPlatformDto.java
  src/main/java/com/bangbangbwa/backend/domain/platform/common/entity/Platform.java
  src/main/java/com/bangbangbwa/backend/domain/platform/controller/PlatformApi.java
  src/main/java/com/bangbangbwa/backend/domain/platform/controller/PlatformController.java
  src/main/java/com/bangbangbwa/backend/domain/platform/exception/NonStreamerPlatformRelation.java
  src/main/java/com/bangbangbwa/backend/domain/platform/exception/type/PlatformErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/platform/repository/PlatformRepository.java
  src/main/java/com/bangbangbwa/backend/domain/platform/service/PlatformService.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/StreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Streamer.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerPlatformListMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/service/StreamerService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/dto/AddPlatformDto.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/controller/StreamerApi.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/controller/StreamerController.java
  src/main/java/com/bangbangbwa/backend/domain/tag/common/mapper/TagMapper.java
  src/main/java/com/bangbangbwa/backend/global/annotation/swagger/ApiResponse401.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/platform.xml
  src/main/resources/mybatis/map/streamer.xml
Labels: documentation, enhancement

#90 [BBB-129] 게시글 미디어 포함 여부 저장
  build.gradle
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostMediaExtractor.java
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostVisibilityProvider.java
  src/main/java/com/bangbangbwa/backend/domain/post/common/entity/Post.java
  src/main/java/com/bangbangbwa/backend/domain/post/common/enums/MediaType.java
  src/main/java/com/bangbangbwa/backend/domain/post/service/PostService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/resources/mybatis/map/post.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/post/PostIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/post/business/PostMediaExtractorTest.java
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
Labels: enhancement

#92 [BBB-128] 답글 관련 API 구현
  src/main/java/com/bangbangbwa/backend/domain/comment/business/CommentReader.java
  src/main/java/com/bangbangbwa/backend/domain/comment/business/CommentUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/comment/common/dto/AddCommentReplyDto.java
  src/main/java/com/bangbangbwa/backend/domain/comment/common/dto/MyPostCommentDto.java
  src/main/java/com/bangbangbwa/backend/domain/comment/controller/CommentController.java
  src/main/java/com/bangbangbwa/backend/domain/comment/exception/NotFoundCommentException.java
  src/main/java/com/bangbangbwa/backend/domain/comment/exception/type/CommentErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/comment/service/CommentService.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/CommentGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/CommentReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/CommentUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Comment.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/CommentRepository.java
  src/main/resources/mybatis/map/comment.xml
  src/main/resources/schema.sql
Labels: enhancement

#94 [BBB-128] CommentController 문서화
  src/main/java/com/bangbangbwa/backend/domain/comment/controller/CommentApi.java
  src/main/java/com/bangbangbwa/backend/domain/comment/controller/CommentController.java
Labels: documentation

#93 [BBB-133] 게시물 목록 조회 미디어 여부 반환
  src/main/java/com/bangbangbwa/backend/domain/post/common/mapper/PostMapper.java
  src/test/java/com/bangbangbwa/backend/domain/post/PostIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/streamer/StreamerTest.java
Labels: enhancement

#96 [BBB-132] 내 게시물 조회 API 구현
  src/main/java/com/bangbangbwa/backend/domain/comment/business/CommentReader.java
  src/main/java/com/bangbangbwa/backend/domain/comment/service/CommentService.java
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/post/common/dto/MyPostDto.java
  src/main/java/com/bangbangbwa/backend/domain/post/controller/PostApi.java
  src/main/java/com/bangbangbwa/backend/domain/post/controller/PostController.java
  src/main/java/com/bangbangbwa/backend/domain/post/service/PostService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/CommentRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PostViewStreamerRepository.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/comment.xml
  src/main/resources/mybatis/map/post.xml
  src/main/resources/mybatis/map/postViewStreamer.xml
Labels: documentation, enhancement

#101 [BBB-132] 스트리머 닉네임 데이터 추가
  src/main/java/com/bangbangbwa/backend/domain/post/common/dto/MyPostDto.java
  src/main/resources/mybatis/map/postViewStreamer.xml
Labels: enhancement

#102 [BBB-136] 프로필 배결 사진 등록/수정/삭제 API 구현
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberUpdateDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberWallpaperDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/mybatis/map/member.xml
  src/main/resources/schema.sql
Labels: documentation, enhancement

#103 [BBB-137] 내가 쓴 댓글 목록 조회 API 구현
  src/main/java/com/bangbangbwa/backend/domain/comment/business/CommentReader.java
  src/main/java/com/bangbangbwa/backend/domain/comment/common/dto/MyCommentDto.java
  src/main/java/com/bangbangbwa/backend/domain/comment/service/CommentService.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/CommentDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/CommentRepository.java
  src/main/resources/mybatis/map/comment.xml
  src/test/java/com/bangbangbwa/backend/domain/member/controller/MemberControllerTest.java
Labels: enhancement

#104 [BBB-135] 회원탈퇴 API 구현
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/platform/repository/StreamerPlatformRepository.java
  src/main/java/com/bangbangbwa/backend/domain/post/business/PostDeleter.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerDeleter.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/PostViewStreamerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/tag/repository/StreamerTagRepository.java
  src/main/resources/mybatis/map/member.xml
  src/main/resources/mybatis/map/post.xml
  src/main/resources/mybatis/map/postViewStreamer.xml
  src/main/resources/mybatis/map/streamerPlatform.xml
  src/main/resources/mybatis/map/streamerTag.xml
Labels: documentation, enhancement
