Repository BangBangBwa/Backend, pull requests merged in 2024-10, with the labels that each got.

#1 [BBB-1] 기본 환경 세팅
  .github/pull_request_template.md
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/bangbangbwa/backend/domain/BasicController.java
  src/main/java/com/bangbangbwa/backend/global/MyBatisConfig.java
  src/main/java/com/bangbangbwa/backend/global/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/format/intellij-java-google-style.xml
  src/main/resources/mybatis/sqlmap-config.xml
Labels: enhancement

#3 [BBB-2] 공통 응답 및 예외 핸들링 처리 구현
  build.gradle
  src/main/java/com/bangbangbwa/backend/domain/BasicController.java
  src/main/java/com/bangbangbwa/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/bangbangbwa/backend/global/error/exception/BusinessException.java
  src/main/java/com/bangbangbwa/backend/global/error/exception/ForbiddenException.java
  src/main/java/com/bangbangbwa/backend/global/error/exception/ServerException.java
  src/main/java/com/bangbangbwa/backend/global/error/exception/UnAuthenticatedException.java
  src/main/java/com/bangbangbwa/backend/global/error/type/ApiErrorType.java
  src/main/java/com/bangbangbwa/backend/global/response/ApiResponse.java
Labels: enhancement

#5 [BBB-3] CI/CD 파이프 라인 구축
  .github/workflows/workflow.dev.yml
  .github/workflows/workflow.feat.yml
  Dockerfile
  src/main/resources/application.yml
  src/main/resources/mybatis/map/.gitkeep
Labels: enhancement

#6 [BBB-11] Swagger 설정
  build.gradle
  src/main/java/com/bangbangbwa/backend/domain/BasicApi.java
  src/main/java/com/bangbangbwa/backend/domain/BasicController.java
  src/main/java/com/bangbangbwa/backend/global/annotation/ApiCommonResponse.java
  src/main/java/com/bangbangbwa/backend/global/config/MyBatisConfig.java
  src/main/java/com/bangbangbwa/backend/global/config/SecurityConfig.java
  src/main/java/com/bangbangbwa/backend/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#8 [BBB-14] 구글 회원 가입
  build.gradle
  src/main/java/com/bangbangbwa/backend/BackendApplication.java
  src/main/java/com/bangbangbwa/backend/domain/BasicController.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/Interest.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/MemberMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/MemberSignupDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/Role.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/InvalidInterestException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/InvalidSnsTypeException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberValidator.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/GoogleInfoFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/KakaoInfoFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/NaverInfoFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthFeignManager.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthInfoProvider.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/GoogleInfoDto.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/OAuthInfoDto.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/SnsType.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/service/OAuthService.java
  src/main/java/com/bangbangbwa/backend/domain/test/TestController.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/AuthProvider.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenProvider.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/TokenDto.java
  src/main/java/com/bangbangbwa/backend/domain/token/service/TokenService.java
  src/main/java/com/bangbangbwa/backend/global/config/FeignConfig.java
  src/main/java/com/bangbangbwa/backend/global/config/SwaggerConfig.java
  src/main/java/com/bangbangbwa/backend/global/config/multipart/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/bangbangbwa/backend/global/util/S3Manager.java
  src/main/resources/application.yml
Labels: bug, enhancement

#10 [BBB-27] LogFilter Multipart 로그 추가
  src/main/java/com/bangbangbwa/backend/global/config/log/CachingRequestWrapper.java
  src/main/java/com/bangbangbwa/backend/global/config/log/LogFilter.java
Labels: bug, enhancement

#11 [BBB-15] 구글 회원가입 & 로그인 Swagger API 구현
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberLoginDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/service/OAuthService.java
Labels: documentation

#12 [BBB-30] 메인페이지 API 명세서 작성
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionApi.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
Labels: documentation, enhancement

#13 [BBB-30] 메인페이지 API 명세서 작성 - Response 이름 수정
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
Labels: documentation

#17 [BBB-36] SNS페이지 더미데이터 API
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetFollowedLatestPostsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostListDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/global/util/randomValue/Language.java
  src/main/java/com/bangbangbwa/backend/global/util/randomValue/RandomValue.java
  src/main/java/com/bangbangbwa/backend/global/util/randomValue/RandomValueGenerator.java
  src/main/java/com/bangbangbwa/backend/global/util/randomValue/StringGenerator.java
Labels: enhancement

#14 [BBB-15] 구글 로그인 비지니스 로직 구현
  build.gradle
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberLoginDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/MemberMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/NotSignupMemberException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/GoogleInfoProvider.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthFeignManager.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthInfoProvider.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/GoogleTokenFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/GoogleTokenDto.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/OAuthInfoDto.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/service/OAuthService.java
  src/main/java/com/bangbangbwa/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/bangbangbwa/backend/global/util/Base64Util.java
  src/main/resources/mybatis/map/member.xml
Labels: documentation, enhancement

#19 [BBB-15] 회원가입 & 로그인 Swagger 수정
  src/main/java/com/bangbangbwa/backend/domain/BasicApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/global/annotation/swagger/ApiCommonResponse.java
  src/main/java/com/bangbangbwa/backend/global/annotation/swagger/ApiResponse200.java
  src/main/java/com/bangbangbwa/backend/global/annotation/swagger/ApiResponse500.java
Labels: documentation

#20 [BBB-4] 닉네임 관련 API 명세서 작성
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberNicknameDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/global/annotation/swagger/ApiResponse200.java
Labels: documentation

#16 [BBB-32] 태그 추가
  src/main/java/com/bangbangbwa/backend/domain/tag/business/TagCreator.java
  src/main/java/com/bangbangbwa/backend/domain/tag/business/TagManager.java
  src/main/java/com/bangbangbwa/backend/domain/tag/business/TagReader.java
  src/main/java/com/bangbangbwa/backend/domain/tag/common/entity/Tag.java
  src/main/java/com/bangbangbwa/backend/domain/tag/repository/TagRepository.java
  src/main/resources/mybatis/map/tag.xml
  src/main/resources/schema.sql
Labels: enhancement

#15 [BBB-34] 테스트 코드 Util 추가
  src/test/java/com/bangbangbwa/backend/global/test/ApplicationContextProvider.java
  src/test/java/com/bangbangbwa/backend/global/test/ContextLoadTest.java
  src/test/java/com/bangbangbwa/backend/global/test/ControllerTest.java
  src/test/java/com/bangbangbwa/backend/global/test/DatabaseCleaner.java
  src/test/java/com/bangbangbwa/backend/global/test/IntegrationTest.java
  src/test/java/com/bangbangbwa/backend/global/test/MyBatisTest.java
  src/test/java/com/bangbangbwa/backend/global/test/ServiceTest.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/Language.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomValue.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomValueGenerator.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/StringGenerator.java
Labels: enhancement

#21 [BBB-4] 닉네임 중복 확인 비지니스 로직 구현
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/DuplicatedNicknameException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/mybatis/map/member.xml
Labels: enhancement

#22 [hotfix/cors] 임시 개발용 CORS 전체 허용
  src/main/java/com/bangbangbwa/backend/global/config/WebConfig.java
Labels: bug, enhancement

#25 [BBB-13] 랜덤 닉네임 제공 비지니스 로직 구현
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/NicknameGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/NicknameProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/MaxNicknameCountExceededException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/NegativeNicknameCountException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/NotExistsRemainNicknameException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/test/java/com/bangbangbwa/backend/domain/NicknameGeneratorTest.java
Labels: enhancement

#24 [BBB-33] 인증/인가/토큰 재발급
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/AuthenticationProvider.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenCreator.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenDeleter.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenProvider.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenReader.java
  src/main/java/com/bangbangbwa/backend/domain/token/business/TokenValidator.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/entity/Token.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/exception/ExpiredTokenException.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/exception/InvalidJwtSignatureException.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/exception/InvalidTokenException.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/exception/NotFoundTokenException.java
  src/main/java/com/bangbangbwa/backend/domain/token/common/exception/type/TokenErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/token/interceptor/AuthInterceptor.java
  src/main/java/com/bangbangbwa/backend/domain/token/repository/TokenRepository.java
  src/main/java/com/bangbangbwa/backend/domain/token/service/TokenService.java
  src/main/java/com/bangbangbwa/backend/global/config/InterceptorConfig.java
  src/main/java/com/bangbangbwa/backend/global/config/SwaggerConfig.java
  src/main/resources/mybatis/map/member.xml
  src/main/resources/mybatis/map/token.xml
  src/main/resources/schema.sql
Labels: enhancement

#26 [BBB-43] 배너 목록 조회 비지니스 로직 구현
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/BannerReader.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Banner.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/BannerMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/BannerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/service/BannerService.java
  src/main/resources/mybatis/map/banner.xml
  src/main/resources/schema.sql
Labels: enhancement
