Repository BangBangBwa/Backend, pull requests merged in 2024-11, with the labels that each got.

#27 [BBB-42] 스트리머 더미 데이터 관련 수정
  src/main/java/com/bangbangbwa/backend/domain/member/common/enums/Role.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/enums/Platform.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
Labels: documentation

#4 [BBB-17] 카카오 회원 가입
  build.gradle
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/KakaoInfoProvider.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthFeignManager.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/KakaoFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/KakaoInfoFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/KakaoTokenFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/KakaoInfoDto.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/KakaoTokenDto.java
Labels: enhancement

#29 [BBB-16] 네이버 회원 가입
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/NaverInfoProvider.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/OAuthFeignManager.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/NaverFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/NaverInfoFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/business/feign/NaverTokenFeign.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/NaverInfoDto.java
  src/main/java/com/bangbangbwa/backend/domain/oauth/common/dto/NaverTokenDto.java
Labels: enhancement

#30 [BBB-49] 토큰 재발급 API 명세서
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
Labels: documentation

#31 [BBB-48] SNS 글쓰기
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/AuthenticationNameNullException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/AuthenticationNullException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/DuplicatedNicknameException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/NotParsedValueException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostCreator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostParser.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/enums/PostType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/NoPostPermission.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/type/PostErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/resources/mybatis/map/post.xml
  src/main/resources/schema.sql
Labels: enhancement

#44 [BBB-73] 마이페이지 조회 API 추가
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/CommentDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/FollowerDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/PostDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/ProfileDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follower.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionBannerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/BannerMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/service/BannerService.java
  src/test/java/com/bangbangbwa/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/service/MemberServiceTest.java
  src/test/java/com/bangbangbwa/backend/global/test/ControllerTest.java
Labels: enhancement

#40 [BBB-77] 댓글 작성 API 명세서 작성
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
Labels: documentation

#39 [BBB-55] 글쓰기 API 명세서 작성
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
Labels: documentation

#41 [BBB-71] 글쓰기 사진/영상 업로드
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostCreator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostUpdater.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostValidator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostVisibilityMemberCreator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostVisibilityMemberGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/CreatePostDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/UploadPostMediaDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/PostVisibilityMember.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/enums/PostStatus.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/enums/VisibilityType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/InvalidMemberVisibilityException.java
  src/main/java/com/bangbangbwa/backend/domain/sns/exception/type/PostErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostVisibilityMemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/resources/mybatis/map/post.xml
  src/main/resources/mybatis/map/postVisibilityMember.xml
  src/main/resources/schema.sql
Labels: enhancement

#45 [BBB-77] 사용자 닉네임 검색
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/MemberMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/EmptyNicknameException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/SearchMemberDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/resources/mybatis/map/member.xml
Labels: enhancement

#49 [BBB-78] 일반 모드 게시물 목록 조회
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostProvider.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostListDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/entity/Post.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/resources/mybatis/map/post.xml
Labels: enhancement

#28 [BBB-42] 추천 방송인 목록 조회 비지니스 로직 구현 1
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberLoginDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/SummaryDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/RandomStreamerProvider.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerParser.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/dto/PromotionStreamerDto.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Platform.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/entity/Streamer.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/enums/Platform.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerInterestedListMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/common/mapper/StreamerPlatformListMapper.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/controller/PromotionController.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerInterestedRepository.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerPlatformRepository.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/service/StreamerService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/entity/Streamer.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/streamer.xml
  src/main/resources/schema.sql
Labels: documentation, enhancement

#48 [BBB-79] 게시글 상세 조회
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/CommentReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/java/com/bangbangbwa/backend/domain/token/interceptor/AuthInterceptor.java
  src/main/java/com/bangbangbwa/backend/global/annotation/authentication/AuthenticationContext.java
  src/main/resources/mybatis/map/post.xml
Labels: enhancement

#52 [BBB-46] 회원 관심태그 등록 비지니스 로직 추가
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberTagRelation.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/MemberSignupDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/mybatis/map/memberTag.xml
  src/main/resources/schema.sql
Labels: enhancement

#51 [BBB-81] 방송인 최신 글 표시
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/business/StreamerReader.java
  src/main/java/com/bangbangbwa/backend/domain/promotion/repository/StreamerRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/business/PostReader.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetLatestPostsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/mapper/PostMapper.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsApi.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/java/com/bangbangbwa/backend/domain/sns/repository/PostRepository.java
  src/main/java/com/bangbangbwa/backend/domain/sns/service/SnsService.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageGenerator.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/business/DailyMessageReader.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/exception/NotFoundStreamerException.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/common/exception/type/StreamerErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/repository/DailyMessageRepository.java
  src/main/java/com/bangbangbwa/backend/domain/streamer/service/DailyMessageService.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/post.xml
  src/main/resources/mybatis/map/streamer.xml
  src/main/resources/schema.sql
Labels: bug, documentation, enhancement

#54 [BBB-75] 마이페이지 조회 비즈니스 로직 작성 - 프로필 조회
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberValidator.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/dto/ProfileDto.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follow.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Follower.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/entity/Member.java
  src/main/java/com/bangbangbwa/backend/domain/member/common/mapper/ProfileMapper.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberApi.java
  src/main/java/com/bangbangbwa/backend/domain/member/controller/MemberController.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/FollowRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/bangbangbwa/backend/domain/member/service/MemberService.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/follow.xml
  src/main/resources/mybatis/map/member.xml
  src/main/resources/schema.sql
  src/test/java/com/bangbangbwa/backend/domain/member/MemberIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/bangbangbwa/backend/domain/member/service/MemberServiceTest.java
  src/test/java/com/bangbangbwa/backend/global/test/DatabaseCleaner.java
  src/test/resources/logback-spring-test.xml
Labels: enhancement

#53 [BBB-86] SNS 페이지 테스트코드
  .github/workflows/workflow.feat.yml
  build.gradle
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberProvider.java
  src/main/java/com/bangbangbwa/backend/domain/member/business/MemberReader.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/EmptyNicknameException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/UnAuthenticationMemberException.java
  src/main/java/com/bangbangbwa/backend/domain/member/exception/type/MemberErrorType.java
  src/main/java/com/bangbangbwa/backend/domain/sns/common/dto/GetPostDetailsDto.java
  src/main/java/com/bangbangbwa/backend/domain/sns/controller/SnsController.java
  src/main/resources/data.sql
  src/main/resources/mybatis/map/comment.xml
  src/main/resources/mybatis/map/post.xml
  src/test/java/com/bangbangbwa/backend/domain/sns/controller/SnsIntegrationTest.java
  src/test/java/com/bangbangbwa/backend/global/test/EmbeddedServer.java
  src/test/java/com/bangbangbwa/backend/global/test/IntegrationTest.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/StringGenerator.java
  src/test/resources/application-test.yml
Labels: enhancement

#56 [BBB-86-fix] 랜덤 문자열 생성을 위한 유틸리티 클래스 추가
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomString.java
  src/test/java/com/bangbangbwa/backend/global/util/randomValue/RandomStringGenerator.java
Labels: documentation, enhancement
